apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240319092919.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240319092919.0.0+build.6aff574
  releaseNotes: |
    Release v20240319092919.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-18-03-2024-21-09-37-450163038/where-for-dinner-my-apps-bundle@sha256:40e479bb2bb6e69a51d5a700e5a63c137d57ab5c076013c47c46ed7934a4afdd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

